name: CI

on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      tag_exists: ${{ steps.check_tag.outputs.EXISTS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          echo 'VERSION<<EOF' >> $GITHUB_ENV
          jq -r '.version' manifest.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Check version
        id: check_version
        run: |
          if [ -z "${VERSION}" ]; then
            echo "VERSION is not set, failing the build."
            exit 1
          else
            echo "VERSION is set to ${VERSION}"
          fi
        shell: bash

      - name: Check if tag exists
        id: check_tag
        run: |
          echo 'EXISTS<<EOF' >> $GITHUB_ENV
          if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo true >> $GITHUB_ENV
          else
            echo false >> $GITHUB_ENV
          fi
          echo 'EOF' >> $GITHUB_ENV

  release:
    needs: prepare
    if: needs.prepare.outputs.tag_exists == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: git tag "v${{ needs.prepare.outputs.version }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.prepare.outputs.version }}
          release_name: v${{ needs.prepare.outputs.version }}
          draft: false
          prerelease: false

  build:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Package extension
        run: web-ext build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: web-ext-artifacts/*.zip

#  publish:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Publish to Firefox Add-ons
#        uses: RobbieGM/addon-action@v1
#        with:
#          zip: web-ext-artifacts/*.zip
#          id: ${{ secrets.ADD_ON_ID }}
#          version: ${{ needs.prepare.outputs.version }}
#          jwt_issuer: ${{ secrets.FIREFOX_API_KEY }}
#          jwt_secret: ${{ secrets.FIREFOX_API_SECRET }}
